/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keystroke;


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static jdk.nashorn.internal.runtime.PropertyMap.diff;

/**
 *
 * @author shehan
 */
public class Register extends javax.swing.JFrame {
    ArrayList keyspress;
    ArrayList keyrelease;
    ArrayList press;
    ArrayList release;
    ArrayList keyseq;
    ArrayList keydiff;
    ArrayList array1; 
    ArrayList array2; 
    ArrayList minarray;
    String name;
    /**
     * Creates new form Register
     */
    public Register() {
        keyspress = new ArrayList<>();
        keyrelease=new ArrayList<>();
        press= new ArrayList<>();
        release=new ArrayList<>();
        keyseq=new ArrayList<>();
        keydiff =new ArrayList<>();
        array1=new ArrayList<>();
        array2=new ArrayList<>();
        minarray=new ArrayList<>();
        name=Firstpage.name;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Remain types");

        jLabel2.setText("3");

        jEditorPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEditorPane1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEditorPane1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Retry");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String attm = jLabel2.getText();
        int attempt = Integer.parseInt(attm);
         for( int i=0 ; i <keyspress.size() ; i++){
          for( int j=0 ; j <keyrelease.size() ; j++){
              if(keyspress.get(i)==keyrelease.get(j)){
                  keyseq.add(keyrelease.get(j));
                   keydiff.add((int) release.get(j)-(int)press.get(i));
                   keyrelease.remove(j);
                   release.remove(j);
                   break;
            }
          }
            
        }
         if (attempt > 1){
             attempt=attempt-1;
            jLabel2.setText(Integer.toString(attempt));
            if(attempt==2){
                array2=keydiff;
                keydiff=new ArrayList<>();
                press= new ArrayList<>();
               keyseq=new ArrayList<>();
            }
            if(attempt==1){
                array1=keydiff;
                keydiff=new ArrayList<>();
                press= new ArrayList<>();
                keyseq=new ArrayList<>();
                for( int i=0 ; i <array1.size() ; i++){
                    System.out.println(array1.get(i));
                }
            }
        }
        else{
          for( int i=0 ; i <keydiff.size() ; i++){
              minarray.add(((int)keydiff.get(i)+(int)array2.get(i)+(int)array1.get(i))/3);
              
          }
                     
 //print all arrays 
 
          System.out.println("record 1");
          for( int i=0 ; i <array1.size() ; i++){
          System.out.println(array1.get(i));
          }
          System.out.println("record 2");
          for( int i=0 ; i <array2.size() ; i++){
          System.out.println(array2.get(i));
         
          }
          System.out.println("record 3");
          for( int i=0 ; i <keydiff.size() ; i++){
          System.out.println(keydiff.get(i));
          }
          System.out.println("records for average press times");
          for( int i=0 ; i <minarray.size() ; i++){
          System.out.println(minarray.get(i));
          }
    //print key sequence       
           System.out.println("keysequence");
           String ptext="";
           String keys="";
          for( int i=0 ; i <keyseq.size() ; i++){
          System.out.println(keyseq.get(i));
          }
           for(int i=0;i<minarray.size();i++){
           ptext=ptext+minarray.get(i)+" ";
        }
        for(int i=0;i<keyseq.size();i++){
           keys=keys+keyseq.get(i);
        }
        database db=new database();
            try {
                db.addData(name, keys, ptext);
                Register.this.setVisible(false);
            Firstpage login = new Firstpage();
            login.show();
            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         
         jEditorPane1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jEditorPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorPane1KeyPressed
        char s = evt.getKeyChar();
        keyspress.add(s);
        int timep = time.currenttime();
        press.add(timep);
    }//GEN-LAST:event_jEditorPane1KeyPressed

    private void jEditorPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEditorPane1KeyReleased
        char s = evt.getKeyChar();
        keyrelease.add(s);
        int timer = time.currenttime();
            release.add(timer);
    }//GEN-LAST:event_jEditorPane1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Register.this.setVisible(false);
         Register login = new Register();
            login.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
